Search.appendIndex(
    [
                {
            "fqsen": "\\App\\DTOs\\OrderDTO",
            "name": "OrderDTO",
            "summary": "Data\u0020Transfer\u0020Object\u0020for\u0020creating\u0020an\u0020Order.",
            "url": "classes/App-DTOs-OrderDTO.html"
        },                {
            "fqsen": "\\App\\DTOs\\OrderDTO\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020OrderDTO\u0020instance.",
            "url": "classes/App-DTOs-OrderDTO.html#method___construct"
        },                {
            "fqsen": "\\App\\DTOs\\OrderDTO\u003A\u003A\u0024user_id",
            "name": "user_id",
            "summary": "",
            "url": "classes/App-DTOs-OrderDTO.html#property_user_id"
        },                {
            "fqsen": "\\App\\DTOs\\OrderDTO\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/App-DTOs-OrderDTO.html#property_type"
        },                {
            "fqsen": "\\App\\DTOs\\OrderDTO\u003A\u003A\u0024weight",
            "name": "weight",
            "summary": "",
            "url": "classes/App-DTOs-OrderDTO.html#property_weight"
        },                {
            "fqsen": "\\App\\DTOs\\OrderDTO\u003A\u003A\u0024price_per_gram",
            "name": "price_per_gram",
            "summary": "",
            "url": "classes/App-DTOs-OrderDTO.html#property_price_per_gram"
        },                {
            "fqsen": "\\App\\Exceptions\\InsufficientBalanceException",
            "name": "InsufficientBalanceException",
            "summary": "Exception\u0020thrown\u0020when\u0020a\u0020user\u0020tries\u0020to\u0020perform\u0020an\u0020action\nrequiring\u0020more\u0020balance\u0020than\u0020is\u0020available\u0020in\u0020their\u0020wallet.",
            "url": "classes/App-Exceptions-InsufficientBalanceException.html"
        },                {
            "fqsen": "\\App\\Exceptions\\InsufficientBalanceException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020InsufficientBalanceException\u0020instance.",
            "url": "classes/App-Exceptions-InsufficientBalanceException.html#method___construct"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper",
            "name": "ResponseHelper",
            "summary": "Class\u0020ResponseHelper\nProvides\u0020standardized\u0020response\u0020formatting\u0020for\u0020the\u0020application.",
            "url": "classes/App-Helpers-ResponseHelper.html"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper\u003A\u003Asuccess\u0028\u0029",
            "name": "success",
            "summary": "Generate\u0020a\u0020successful\u0020response.",
            "url": "classes/App-Helpers-ResponseHelper.html#method_success"
        },                {
            "fqsen": "\\App\\Helpers\\ResponseHelper\u003A\u003Aerror\u0028\u0029",
            "name": "error",
            "summary": "Generate\u0020an\u0020error\u0020response.",
            "url": "classes/App-Helpers-ResponseHelper.html#method_error"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController",
            "name": "LoginController",
            "summary": "Class\u0020LoginController",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "LoginController\u0020constructor.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Handle\u0020a\u0020login\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#method_login"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\LoginController\u003A\u003A\u0024authenticateService",
            "name": "authenticateService",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-LoginController.html#property_authenticateService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController",
            "name": "RegisterController",
            "summary": "Class\u0020RegisterController",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "RegisterController\u0020constructor.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Handle\u0020a\u0020user\u0020registration\u0020request.",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#method_register"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth\\RegisterController\u003A\u003A\u0024authenticateService",
            "name": "authenticateService",
            "summary": "",
            "url": "classes/App-Http-Controllers-Auth-RegisterController.html#property_authenticateService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/App-Http-Controllers-Controller.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController",
            "name": "OrderController",
            "summary": "Class\u0020OrderController",
            "url": "classes/App-Http-Controllers-Order-OrderController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "OrderController\u0020constructor.",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003Aindex\u0028\u0029",
            "name": "index",
            "summary": "Display\u0020a\u0020listing\u0020of\u0020the\u0020authenticated\u0020user\u0027s\u0020orders.",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#method_index"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003Astore\u0028\u0029",
            "name": "store",
            "summary": "Store\u0020a\u0020new\u0020order\u0020for\u0020the\u0020authenticated\u0020user.",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#method_store"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003Acancel\u0028\u0029",
            "name": "cancel",
            "summary": "Cancel\u0020a\u0020given\u0020order\u0020after\u0020checking\u0020authorization.",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#method_cancel"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003A\u0024goldPrice",
            "name": "goldPrice",
            "summary": "Default\u0020gold\u0020price\u0020per\u0020gram.",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#property_goldPrice"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003A\u0024orderService",
            "name": "orderService",
            "summary": "",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#property_orderService"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order\\OrderController\u003A\u003A\u0024orderRepository",
            "name": "orderRepository",
            "summary": "",
            "url": "classes/App-Http-Controllers-Order-OrderController.html#property_orderRepository"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Wallet\\WalletController",
            "name": "WalletController",
            "summary": "Class\u0020WalletController",
            "url": "classes/App-Http-Controllers-Wallet-WalletController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Wallet\\WalletController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "WalletController\u0020constructor.",
            "url": "classes/App-Http-Controllers-Wallet-WalletController.html#method___construct"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Wallet\\WalletController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Show\u0020the\u0020wallet\u0020information\u0020of\u0020a\u0020specific\u0020user.",
            "url": "classes/App-Http-Controllers-Wallet-WalletController.html#method_show"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Wallet\\WalletController\u003A\u003A\u0024repository",
            "name": "repository",
            "summary": "The\u0020wallet\u0020repository\u0020instance.",
            "url": "classes/App-Http-Controllers-Wallet-WalletController.html#property_repository"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreOrderRequest",
            "name": "StoreOrderRequest",
            "summary": "Class\u0020StoreOrderRequest",
            "url": "classes/App-Http-Requests-StoreOrderRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreOrderRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-StoreOrderRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\StoreOrderRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-StoreOrderRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserLoginRequest",
            "name": "UserLoginRequest",
            "summary": "Class\u0020UserLoginRequest",
            "url": "classes/App-Http-Requests-UserLoginRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserLoginRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-UserLoginRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserLoginRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-UserLoginRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserRegisterRequest",
            "name": "UserRegisterRequest",
            "summary": "Class\u0020UserRegisterRequest",
            "url": "classes/App-Http-Requests-UserRegisterRequest.html"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserRegisterRequest\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020is\u0020authorized\u0020to\u0020make\u0020this\u0020request.",
            "url": "classes/App-Http-Requests-UserRegisterRequest.html#method_authorize"
        },                {
            "fqsen": "\\App\\Http\\Requests\\UserRegisterRequest\u003A\u003Arules\u0028\u0029",
            "name": "rules",
            "summary": "Get\u0020the\u0020validation\u0020rules\u0020that\u0020apply\u0020to\u0020the\u0020request.",
            "url": "classes/App-Http-Requests-UserRegisterRequest.html#method_rules"
        },                {
            "fqsen": "\\App\\Http\\Resources\\OrderResource",
            "name": "OrderResource",
            "summary": "Class\u0020OrderResource",
            "url": "classes/App-Http-Resources-OrderResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\OrderResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-OrderResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\TransactionResource",
            "name": "TransactionResource",
            "summary": "Class\u0020TransactionResource",
            "url": "classes/App-Http-Resources-TransactionResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\TransactionResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-TransactionResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource",
            "name": "UserResource",
            "summary": "Class\u0020UserResource",
            "url": "classes/App-Http-Resources-UserResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\UserResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020resource\u0020into\u0020an\u0020array.",
            "url": "classes/App-Http-Resources-UserResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Http\\Resources\\WalletResource",
            "name": "WalletResource",
            "summary": "Class\u0020WalletResource",
            "url": "classes/App-Http-Resources-WalletResource.html"
        },                {
            "fqsen": "\\App\\Http\\Resources\\WalletResource\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Transform\u0020the\u0020wallet\u0020resource\u0020into\u0020an\u0020array\u0020suitable\u0020for\u0020JSON\u0020output.",
            "url": "classes/App-Http-Resources-WalletResource.html#method_toArray"
        },                {
            "fqsen": "\\App\\Models\\Order",
            "name": "Order",
            "summary": "",
            "url": "classes/App-Models-Order.html"
        },                {
            "fqsen": "\\App\\Models\\Order\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020the\u0020user\u0020that\u0020owns\u0020the\u0020order.",
            "url": "classes/App-Models-Order.html#method_user"
        },                {
            "fqsen": "\\App\\Models\\Order\u003A\u003Atransactions\u0028\u0029",
            "name": "transactions",
            "summary": "Get\u0020the\u0020transactions\u0020that\u0020own\u0020the\u0020order.",
            "url": "classes/App-Models-Order.html#method_transactions"
        },                {
            "fqsen": "\\App\\Models\\Order\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Order.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Transaction",
            "name": "Transaction",
            "summary": "",
            "url": "classes/App-Models-Transaction.html"
        },                {
            "fqsen": "\\App\\Models\\Transaction\u003A\u003Abuyer\u0028\u0029",
            "name": "buyer",
            "summary": "Get\u0020the\u0020buyer\u0020associated\u0020with\u0020the\u0020transaction.",
            "url": "classes/App-Models-Transaction.html#method_buyer"
        },                {
            "fqsen": "\\App\\Models\\Transaction\u003A\u003Aseller\u0028\u0029",
            "name": "seller",
            "summary": "Get\u0020the\u0020seller\u0020associated\u0020with\u0020the\u0020transaction.",
            "url": "classes/App-Models-Transaction.html#method_seller"
        },                {
            "fqsen": "\\App\\Models\\Transaction\u003A\u003Aorder\u0028\u0029",
            "name": "order",
            "summary": "Get\u0020the\u0020original\u0020order\u0020associated\u0020with\u0020the\u0020transaction.",
            "url": "classes/App-Models-Transaction.html#method_order"
        },                {
            "fqsen": "\\App\\Models\\Transaction\u003A\u003AmatchOrder\u0028\u0029",
            "name": "matchOrder",
            "summary": "Get\u0020the\u0020matching\u0020order\u0020that\u0020was\u0020fulfilled\u0020in\u0020the\u0020transaction.",
            "url": "classes/App-Models-Transaction.html#method_matchOrder"
        },                {
            "fqsen": "\\App\\Models\\Transaction\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Transaction.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Models-User.html"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Acasts\u0028\u0029",
            "name": "casts",
            "summary": "Get\u0020the\u0020attributes\u0020that\u0020should\u0020be\u0020cast.",
            "url": "classes/App-Models-User.html#method_casts"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Awallet\u0028\u0029",
            "name": "wallet",
            "summary": "Get\u0020the\u0020wallet\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Models-User.html#method_wallet"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003Aorders\u0028\u0029",
            "name": "orders",
            "summary": "Get\u0020the\u0020orders\u0020associated\u0020with\u0020the\u0020user.",
            "url": "classes/App-Models-User.html#method_orders"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-User.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\User\u003A\u003A\u0024hidden",
            "name": "hidden",
            "summary": "The\u0020attributes\u0020that\u0020should\u0020be\u0020hidden\u0020for\u0020serialization.",
            "url": "classes/App-Models-User.html#property_hidden"
        },                {
            "fqsen": "\\App\\Models\\Wallet",
            "name": "Wallet",
            "summary": "",
            "url": "classes/App-Models-Wallet.html"
        },                {
            "fqsen": "\\App\\Models\\Wallet\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "Get\u0020the\u0020user\u0020associated\u0020with\u0020the\u0020wallet.",
            "url": "classes/App-Models-Wallet.html#method_user"
        },                {
            "fqsen": "\\App\\Models\\Wallet\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "The\u0020attributes\u0020that\u0020are\u0020mass\u0020assignable.",
            "url": "classes/App-Models-Wallet.html#property_fillable"
        },                {
            "fqsen": "\\App\\Policies\\OrderPolicy",
            "name": "OrderPolicy",
            "summary": "",
            "url": "classes/App-Policies-OrderPolicy.html"
        },                {
            "fqsen": "\\App\\Policies\\OrderPolicy\u003A\u003Acancel\u0028\u0029",
            "name": "cancel",
            "summary": "Determine\u0020if\u0020the\u0020user\u0020can\u0020cancel\u0020the\u0020order.",
            "url": "classes/App-Policies-OrderPolicy.html#method_cancel"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy",
            "name": "WalletPolicy",
            "summary": "",
            "url": "classes/App-Policies-WalletPolicy.html"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003AviewAny\u0028\u0029",
            "name": "viewAny",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020view\u0020any\u0020models.",
            "url": "classes/App-Policies-WalletPolicy.html#method_viewAny"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003Aview\u0028\u0029",
            "name": "view",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020view\u0020the\u0020model.",
            "url": "classes/App-Policies-WalletPolicy.html#method_view"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020create\u0020models.",
            "url": "classes/App-Policies-WalletPolicy.html#method_create"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020update\u0020the\u0020model.",
            "url": "classes/App-Policies-WalletPolicy.html#method_update"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020delete\u0020the\u0020model.",
            "url": "classes/App-Policies-WalletPolicy.html#method_delete"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003Arestore\u0028\u0029",
            "name": "restore",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020restore\u0020the\u0020model.",
            "url": "classes/App-Policies-WalletPolicy.html#method_restore"
        },                {
            "fqsen": "\\App\\Policies\\WalletPolicy\u003A\u003AforceDelete\u0028\u0029",
            "name": "forceDelete",
            "summary": "Determine\u0020whether\u0020the\u0020user\u0020can\u0020permanently\u0020delete\u0020the\u0020model.",
            "url": "classes/App-Policies-WalletPolicy.html#method_forceDelete"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface",
            "name": "OrderRepositoryInterface",
            "summary": "Interface\u0020OrderRepositoryInterface",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020order\u0020in\u0020the\u0020database.",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface\u003A\u003AfindOpenMatches\u0028\u0029",
            "name": "findOpenMatches",
            "summary": "Find\u0020open\u0020orders\u0020that\u0020match\u0020the\u0020given\u0020type\u0020and\u0020price.",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html#method_findOpenMatches"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface\u003A\u003AupdateRemainingWeight\u0028\u0029",
            "name": "updateRemainingWeight",
            "summary": "Update\u0020the\u0020remaining\u0020weight\u0020of\u0020an\u0020order.",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html#method_updateRemainingWeight"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface\u003A\u003AgetAllOrders\u0028\u0029",
            "name": "getAllOrders",
            "summary": "Get\u0020all\u0020orders\u0020associated\u0020with\u0020a\u0020specific\u0020user.",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html#method_getAllOrders"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\OrderRepositoryInterface\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020order\u0020with\u0020the\u0020provided\u0020data.",
            "url": "classes/App-Repositories-Interfaces-OrderRepositoryInterface.html#method_update"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\UserRepositoryInterface",
            "name": "UserRepositoryInterface",
            "summary": "Interface\u0020UserRepositoryInterface",
            "url": "classes/App-Repositories-Interfaces-UserRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\UserRepositoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user\u0020record.",
            "url": "classes/App-Repositories-Interfaces-UserRepositoryInterface.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\UserRepositoryInterface\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020email\u0020address.",
            "url": "classes/App-Repositories-Interfaces-UserRepositoryInterface.html#method_findByEmail"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\UserRepositoryInterface\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020ID.",
            "url": "classes/App-Repositories-Interfaces-UserRepositoryInterface.html#method_findById"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\WalletRepositoryInterface",
            "name": "WalletRepositoryInterface",
            "summary": "Interface\u0020WalletRepositoryInterface",
            "url": "classes/App-Repositories-Interfaces-WalletRepositoryInterface.html"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces\\WalletRepositoryInterface\u003A\u003AgetWalletByUser\u0028\u0029",
            "name": "getWalletByUser",
            "summary": "Retrieve\u0020a\u0020wallet\u0020instance\u0020by\u0020the\u0020given\u0020user\u0020ID.",
            "url": "classes/App-Repositories-Interfaces-WalletRepositoryInterface.html#method_getWalletByUser"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository",
            "name": "OrderRepository",
            "summary": "Class\u0020OrderRepository",
            "url": "classes/App-Repositories-OrderRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020order\u0020in\u0020the\u0020database.",
            "url": "classes/App-Repositories-OrderRepository.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository\u003A\u003AfindOpenMatches\u0028\u0029",
            "name": "findOpenMatches",
            "summary": "Find\u0020open\u0020orders\u0020that\u0020match\u0020the\u0020given\u0020type\u0020and\u0020price.",
            "url": "classes/App-Repositories-OrderRepository.html#method_findOpenMatches"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository\u003A\u003AupdateRemainingWeight\u0028\u0029",
            "name": "updateRemainingWeight",
            "summary": "Update\u0020the\u0020remaining\u0020weight\u0020of\u0020an\u0020order.",
            "url": "classes/App-Repositories-OrderRepository.html#method_updateRemainingWeight"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository\u003A\u003AgetAllOrders\u0028\u0029",
            "name": "getAllOrders",
            "summary": "Get\u0020all\u0020orders\u0020associated\u0020with\u0020a\u0020specific\u0020user.",
            "url": "classes/App-Repositories-OrderRepository.html#method_getAllOrders"
        },                {
            "fqsen": "\\App\\Repositories\\OrderRepository\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Update\u0020the\u0020specified\u0020order\u0020with\u0020the\u0020provided\u0020data.",
            "url": "classes/App-Repositories-OrderRepository.html#method_update"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/App-Repositories-UserRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Create\u0020a\u0020new\u0020user\u0020record.",
            "url": "classes/App-Repositories-UserRepository.html#method_create"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003AfindByEmail\u0028\u0029",
            "name": "findByEmail",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020email\u0020address.",
            "url": "classes/App-Repositories-UserRepository.html#method_findByEmail"
        },                {
            "fqsen": "\\App\\Repositories\\UserRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "Find\u0020a\u0020user\u0020by\u0020their\u0020ID.",
            "url": "classes/App-Repositories-UserRepository.html#method_findById"
        },                {
            "fqsen": "\\App\\Repositories\\WalletRepository",
            "name": "WalletRepository",
            "summary": "",
            "url": "classes/App-Repositories-WalletRepository.html"
        },                {
            "fqsen": "\\App\\Repositories\\WalletRepository\u003A\u003AgetWalletByUser\u0028\u0029",
            "name": "getWalletByUser",
            "summary": "Retrieve\u0020a\u0020wallet\u0020instance\u0020by\u0020the\u0020given\u0020user\u0020ID.",
            "url": "classes/App-Repositories-WalletRepository.html#method_getWalletByUser"
        },                {
            "fqsen": "\\App\\Services\\AuthenticationService",
            "name": "AuthenticationService",
            "summary": "Class\u0020AuthenticationService",
            "url": "classes/App-Services-AuthenticationService.html"
        },                {
            "fqsen": "\\App\\Services\\AuthenticationService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AuthenticationService\u0020constructor.",
            "url": "classes/App-Services-AuthenticationService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\AuthenticationService\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Attempt\u0020to\u0020authenticate\u0020a\u0020user\u0020with\u0020the\u0020given\u0020credentials.",
            "url": "classes/App-Services-AuthenticationService.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Services\\AuthenticationService\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020a\u0020new\u0020user\u0020with\u0020the\u0020given\u0020credentials.",
            "url": "classes/App-Services-AuthenticationService.html#method_register"
        },                {
            "fqsen": "\\App\\Services\\AuthenticationService\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/App-Services-AuthenticationService.html#property_userRepository"
        },                {
            "fqsen": "\\App\\Services\\Interfaces\\AuthenticationServiceInterface",
            "name": "AuthenticationServiceInterface",
            "summary": "Interface\u0020AuthenticationServiceInterface",
            "url": "classes/App-Services-Interfaces-AuthenticationServiceInterface.html"
        },                {
            "fqsen": "\\App\\Services\\Interfaces\\AuthenticationServiceInterface\u003A\u003Aauthenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "Attempts\u0020to\u0020authenticate\u0020a\u0020user\u0020with\u0020the\u0020provided\u0020credentials.",
            "url": "classes/App-Services-Interfaces-AuthenticationServiceInterface.html#method_authenticate"
        },                {
            "fqsen": "\\App\\Services\\Interfaces\\AuthenticationServiceInterface\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Registers\u0020a\u0020new\u0020user\u0020with\u0020the\u0020provided\u0020credentials.",
            "url": "classes/App-Services-Interfaces-AuthenticationServiceInterface.html#method_register"
        },                {
            "fqsen": "\\App\\Services\\Interfaces\\OrderServiceInterface",
            "name": "OrderServiceInterface",
            "summary": "Interface\u0020OrderServiceInterface",
            "url": "classes/App-Services-Interfaces-OrderServiceInterface.html"
        },                {
            "fqsen": "\\App\\Services\\Interfaces\\OrderServiceInterface\u003A\u003AplaceOrder\u0028\u0029",
            "name": "placeOrder",
            "summary": "Places\u0020a\u0020new\u0020order\u0020based\u0020on\u0020the\u0020provided\u0020data.",
            "url": "classes/App-Services-Interfaces-OrderServiceInterface.html#method_placeOrder"
        },                {
            "fqsen": "\\App\\Services\\Order\\Commission\\CommissionStrategy",
            "name": "CommissionStrategy",
            "summary": "Interface\u0020CommissionStrategy",
            "url": "classes/App-Services-Order-Commission-CommissionStrategy.html"
        },                {
            "fqsen": "\\App\\Services\\Order\\Commission\\CommissionStrategy\u003A\u003Acalculate\u0028\u0029",
            "name": "calculate",
            "summary": "Calculate\u0020the\u0020commission\u0020for\u0020a\u0020given\u0020order.",
            "url": "classes/App-Services-Order-Commission-CommissionStrategy.html#method_calculate"
        },                {
            "fqsen": "\\App\\Services\\Order\\Commission\\DefaultCommissionStrategy",
            "name": "DefaultCommissionStrategy",
            "summary": "Class\u0020DefaultCommissionStrategy",
            "url": "classes/App-Services-Order-Commission-DefaultCommissionStrategy.html"
        },                {
            "fqsen": "\\App\\Services\\Order\\Commission\\DefaultCommissionStrategy\u003A\u003Acalculate\u0028\u0029",
            "name": "calculate",
            "summary": "Calculate\u0020the\u0020commission\u0020based\u0020on\u0020weight\u0020and\u0020price\u0020per\u0020gram.",
            "url": "classes/App-Services-Order-Commission-DefaultCommissionStrategy.html#method_calculate"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService",
            "name": "OrderService",
            "summary": "Service\u0020responsible\u0020for\u0020handling\u0020order\u0020placement\u0020and\u0020validation\u0020logic.",
            "url": "classes/App-Services-Order-OrderService.html"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Services-Order-OrderService.html#method___construct"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003AplaceOrder\u0028\u0029",
            "name": "placeOrder",
            "summary": "Places\u0020a\u0020new\u0020order\u0020and\u0020attempts\u0020to\u0020match\u0020it\u0020with\u0020existing\u0020opposite\u0020orders.",
            "url": "classes/App-Services-Order-OrderService.html#method_placeOrder"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003AvalidateUserBalance\u0028\u0029",
            "name": "validateUserBalance",
            "summary": "Validates\u0020whether\u0020the\u0020user\u0020has\u0020enough\u0020balance\u0020\u0028rial\u0020or\u0020gold\u0029\u0020to\u0020place\u0020an\u0020order.",
            "url": "classes/App-Services-Order-OrderService.html#method_validateUserBalance"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003AupdateOrderStatus\u0028\u0029",
            "name": "updateOrderStatus",
            "summary": "Updates\u0020the\u0020status\u0020of\u0020an\u0020order\u0020based\u0020on\u0020its\u0020remaining\u0020weight.",
            "url": "classes/App-Services-Order-OrderService.html#method_updateOrderStatus"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003A\u0024orderRepository",
            "name": "orderRepository",
            "summary": "",
            "url": "classes/App-Services-Order-OrderService.html#property_orderRepository"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003A\u0024walletAdjustmentService",
            "name": "walletAdjustmentService",
            "summary": "",
            "url": "classes/App-Services-Order-OrderService.html#property_walletAdjustmentService"
        },                {
            "fqsen": "\\App\\Services\\Order\\OrderService\u003A\u003A\u0024commissionStrategy",
            "name": "commissionStrategy",
            "summary": "",
            "url": "classes/App-Services-Order-OrderService.html#property_commissionStrategy"
        },                {
            "fqsen": "\\App\\Services\\Order\\WalletAdjustmentService",
            "name": "WalletAdjustmentService",
            "summary": "Class\u0020WalletAdjustmentService",
            "url": "classes/App-Services-Order-WalletAdjustmentService.html"
        },                {
            "fqsen": "\\App\\Services\\Order\\WalletAdjustmentService\u003A\u003Aadjust\u0028\u0029",
            "name": "adjust",
            "summary": "Adjusts\u0020the\u0020wallets\u0020of\u0020the\u0020buyer\u0020and\u0020the\u0020seller\u0020based\u0020on\u0020transaction\u0020details.",
            "url": "classes/App-Services-Order-WalletAdjustmentService.html#method_adjust"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\DTOs",
            "name": "DTOs",
            "summary": "",
            "url": "namespaces/app-dtos.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/app-exceptions.html"
        },                {
            "fqsen": "\\App\\Helpers",
            "name": "Helpers",
            "summary": "",
            "url": "namespaces/app-helpers.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "namespaces/app-http-controllers-auth.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Order",
            "name": "Order",
            "summary": "",
            "url": "namespaces/app-http-controllers-order.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\Wallet",
            "name": "Wallet",
            "summary": "",
            "url": "namespaces/app-http-controllers-wallet.html"
        },                {
            "fqsen": "\\App\\Http\\Requests",
            "name": "Requests",
            "summary": "",
            "url": "namespaces/app-http-requests.html"
        },                {
            "fqsen": "\\App\\Http\\Resources",
            "name": "Resources",
            "summary": "",
            "url": "namespaces/app-http-resources.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Policies",
            "name": "Policies",
            "summary": "",
            "url": "namespaces/app-policies.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\App\\Repositories\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/app-repositories-interfaces.html"
        },                {
            "fqsen": "\\App\\Repositories",
            "name": "Repositories",
            "summary": "",
            "url": "namespaces/app-repositories.html"
        },                {
            "fqsen": "\\App\\Services",
            "name": "Services",
            "summary": "",
            "url": "namespaces/app-services.html"
        },                {
            "fqsen": "\\App\\Services\\Interfaces",
            "name": "Interfaces",
            "summary": "",
            "url": "namespaces/app-services-interfaces.html"
        },                {
            "fqsen": "\\App\\Services\\Order\\Commission",
            "name": "Commission",
            "summary": "",
            "url": "namespaces/app-services-order-commission.html"
        },                {
            "fqsen": "\\App\\Services\\Order",
            "name": "Order",
            "summary": "",
            "url": "namespaces/app-services-order.html"
        }            ]
);
